[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "CountrXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

[programs.devnet]
counter = "CountrXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

[programs.mainnet]
counter = "CountrXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
